import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import "./globals.scss";
import "remixicon/fonts/remixicon.css";
import { WhatsApp } from "@/components/WhatsApp";
import { Loader } from "@/components/Loader";
import { ScrollToTop } from "@/components/ScrollToTop";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon: "/fitgreen-logo.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Loader/>
        <Header/>
        {children}
        <WhatsApp/>
        <ScrollToTop/>
        <Footer/>
      </body>
    </html>
  );
}
